### ISSUE TITLE
Add actor command for extra fits header parameters.

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmcam#44]
Dont know what instrument parameters should go into the fits header, but the more the better.
so a general function to do that whould be nice to have - [see here](https://github.com/sdss/cluplus/wiki/Introduction#filling-the-fits-header)

**Comment by wasndas** [comment]
Actually, the idea was to have an extra header that can be passed from upper level (eg. lvmagp) through the actor interface,
similar to [archon](https://github.com/sdss/archon/blob/c28080d145072dc80dedff111d6d589a7fd195ff/archon/actor/commands/expose.py#L142) and used from [lvmscp](https://github.com/sdss/lvmscp/blob/651e22c8e352fff53627b9be9a88cd97dc96c32a/python/lvmscp/actor/commands/exposure.py#L122) (see also [lvmscp](https://github.com/sdss/lvmscp/blob/651e22c8e352fff53627b9be9a88cd97dc96c32a/python/lvmscp/actor/commands/exposure.py#L191)), an alternative implementation whould be the way I have pointed out at the beginning of this ticket. At that time I didnt know Jose has already done somethin similar.

**Comment by mgjeon** [comment]
I've made [`--header` option](https://sdss-lvmcam.readthedocs.io/en/latest/example.html#extra-header) similar to archon on lvmcam 0.2.1.
