### ISSUE TITLE
How do I start lvmcam ?

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmcam#50]
Tried it with and without config file.
**poetry run lvmcam -v start  --debug**
**poetry run lvmcam --config=python/lvmcam/etc/cameras.yaml -v start  --debug**

- checked camtype.yml: skymakercam: True & araviscam: False
- when starting with config file cameras.yaml , I had to add the the actor stuff from the defaul config lvmcam.yml

The result is always:

```
lvmcam list
07:24:18.968 lvmcam >
07:24:18.981 lvmcam e {
    "error": "Failed validating the reply: message {'cameras': [], 'default_cameras': None} does not match the schema."
}
```

**Comment by mgjeon** [comment]
Currently `lvmcam list` command is unavailable, instead you can use `lvmcam show all`. 

You can start lvmcam as follows. If you still were in trouble with starting lvmcam, please let me know.

1. Start directly
```
$ lvmcam start --debug
```

2. Use docker image
```
$ poetry run container_start --kill --name=lvm.cam
```

**Comment by mgjeon** [comment]
> Currently `lvmcam list` command is unavailable, instead you can use `lvmcam show all`.
> 
> You can start lvmcam as follows. If you still were in trouble with starting lvmcam, please let me know.
> 
> 1. Start directly
> 
> ```
> $ lvmcam start --debug
> ```
> 
> 2. Use docker image
> 
> ```
> $ poetry run container_start --kill --name=lvm.cam
> ```

If everything is fine, you can get an image by using a below command.
```
$ clu
lvmcam connect -n lvm.sci.agw.cam
lvmcam expose 5 1 lvm.sci.agw.cam
```

**Comment by mgjeon** [comment]
> Currently `lvmcam list` command is unavailable, instead you can use `lvmcam show all`.
> 
> You can start lvmcam as follows. If you still were in trouble with starting lvmcam, please let me know.
> 
> 1. Start directly
> 
> ```
> $ lvmcam start --debug
> ```
> 
> 2. Use docker image
> 
> ```
> $ poetry run container_start --kill --name=lvm.cam
> ```

I'm sorry. I forgot to say that for connecting skymakercam, you have to flag `--virtual` option when starting lvmcam using docker image.

 ```
 $ poetry run container_start --virtual --kill --name=lvm.cam
 ```

And if you want to start lvmcam directly, you have to change `python/lvmcam/etc/camtype.yaml` file as follows.

```
camtype:
    araviscam: False
    skymakercam: True
```

**Comment by wasndas** [comment]
done
